### ISSUE TITLE
Inheritence arrows in UML diagram

### ISSUE THREAD

**Issue by KarolisCremers** [Health-RI/health-ri-metadata#117]
The inheritence arrows (with a white filled arrowhead) are not following the same pattern as DCAT-AP 3.0:
https://semiceu.github.io/DCAT-AP/releases/3.0.0/#application-profile-diagram

What is catalog inheriting from dataset? Description and publisher?
Am I misunderstanding the arrows?

**Comment by Markus92** [comment]
Catalog is inherited from Dataset, see also the DCAT-3 spec: https://www.w3.org/TR/vocab-dcat-3/

**Comment by KarolisCremers** [comment]
So you're using the DCAT-3 specs and not the DCAT-AP specs? Just to be sure, please provide the link to the specifications you're using on the main info page of the git.

**Comment by Markus92** [comment]
As you know, DCAT-AP 3 is based on DCAT 3 (see section 1.2). Section 7.2 of the DCAT-AP 3 specification refers that when they refer to Catalog, they refer to Catalog in DCAT-3 (and link to Section 6.3 of the DCAT-3 specs). The DCAT-AP working group only considers constraints to be in their scope. They do not further restrict this inheritance. Or maybe they just forgot to update their UML?

Anyways this inheritance has been there since DCAT-2 so it's quite established by now.
