### ISSUE TITLE
[core shapes] question on catalog title property

### ISSUE THREAD

**Issue by kburger** [Health-RI/health-ri-metadata#37]
https://github.com/Health-RI/health-ri-metadata/blob/4cd351a9e6c178c64e92413a188c14a6652c1061/Metadata%20Schemas%20(Formal%20models)/Core%20Metadata%20Model/core.shapes.ttl#L107-L112

Using this property as an example, some general points:

- `sh:Violation` is the default severity, do we want to explicitly define this everywhere?
- these shapes are generated by topbraid, does it allow for more specific definitions like `sh:uniqueLang` which are required to make this definition work for this example property?

**Comment by denatahvildari** [comment]
@kburger 
- If you are making validation reports for the metadata providing system (source), then yes i think it is needed to be defined on each properties. 
- yes you can define`sh:uniqueLang` with composer as ConstraintComponent. Do you want to activate it? because if yes, it indicates that for each instance of the target class, the values of the specified property must have unique language tags. is this the case in the metadata graph? 
-if yes, I can add them
