### ISSUE TITLE
[core shapes] DataService endpointDescription property contradictions

### ISSUE THREAD

**Issue by kburger** [Health-RI/health-ri-metadata#53]
https://github.com/Health-RI/health-ri-metadata/blob/c4648a69ac6cf660515808f7321ec2d706509a97/Foraml%20Models%20(shapes%2C%20rdf%2C%20skos%2C)/Core%20Metadata%20Module/coreRules.shapes.ttl#L148-L155

1. We need to make a decision on whether to support and/or promote the use of blank nodes.
2. In this specific case there is a disconnect between the type constraint (bnode or iri) and the dash directives (which expect the type to be a literal kind).

**Comment by denatahvildari** [comment]
1. Agree -- We need to understand the specific use case:  in general bnodes can be useful for representing data where the exact identity is unknown. However, they can also make data less interoperable and harder to merge with other datasets because they lack a global identifier. so we need to evaluate the impact on data linking and stuff for future.. 
 

2. For now i change the sh:nodeKind to  to sh:LiteralOrIRI. Is then the `**dash:viewer dash:URIViewer ;** ` correct? 

the code will be: 

```
 ], [ 
     sh:path <http://www.w3.org/ns/dcat#endpointDescription> ; 
     **sh:nodeKind sh:LiteralOrIRI ;** 
     sh:severity sh:Violation ; 
     dash:editor dash:TextAreaEditor ; 
     dash:viewer dash:URIViewer ;  --> #because it needs to be resolved as IRI in case of Pointing to an API
 ], [ 
```

**Comment by PatrickDekkerHealthRI** [comment]
Can you check id this done and close the ticket ?

**Comment by xiaofengleo** [comment]
in the current diagram https://github.com/Health-RI/health-ri-metadata, the dcat:endpointDescription is rdfs:Literal.
The current shape aligns with this definition.

I think this issues can be closed.
