### ISSUE TITLE
export for byCovid conflicts

### ISSUE THREAD

**Issue by brunasv** [Health-RI/health-ri-metadata#8]
- [x] we are not adding publisher to Catalog level, because for Covid Catalog is focus area and there cannot be a publisher.
- [ ] License is not always provided (some projects do not have datasets hence there’s no license) – shouldn’t it be optional?
- [x] For ByCovid export we were asked to provide creator and contactPoint information as vCard. Do you think it is reasonable to include that in the model as an option?

**Comment by denatahvildari** [comment]
--> we are not adding publisher to Catalog level, because for Covid Catalog is focus area and there cannot be a publisher.
**agreed**

 License is not always provided (some projects do not have datasets hence there’s no license) – shouldn’t it be optional?
**Cannot be optional (license are defined on the dataset class)** 

 For ByCovid export we were asked to provide creator and contactPoint information as vCard. Do you think it is reasonable to include that in the model as an option?
**FOAF namespace is what we use for this**
